load("@rules_pkg//:mappings.bzl", "pkg_files")

package(default_visibility = ["//visibility:public"])

pkg_files(
    name = "launchd",
    srcs = [
        "cc.colorto.basil-tonic.plist",
    ],
    prefix = "Library/LaunchAgents",
)
